u_ref: 1.0
chord: 1.0
pvt: 0.33
cm_pvt: 0.33
foil_name: "../naca0015_airfoil.dat"
re_ref: 1000
lesp_crit: 0.19
motion_file_name: "motion_pr_amp45_k0.2.dat"
force_file_name: "force_pr_amp45_k0.2_le.csv"
flow_file_name: "flow.csv"
n_pts_flow: 100
n_period: 5
rho: 1.225
nu: 1.566e-5
n_div: 70
max_iter: 1000
pop_size: 24
n_generations: 400
up_bound: [0.8,1.4,1.0,3.141592653589793]
low_bound: [0.1,0,0,-3.141592653589793]